language: python
python:
  - 3.7
before_install:
  - chmod -R 777 .
install:
  - pip install -r ./client/requirements.txt
branches:
  only: ["master"]
jobs:
  include:
    - stage: client
      script: ./client/test/travis_entrypoint.sh
    - stage: server
      script: ./server/test/travis_entrypoint.sh
    - stage: db
      script: ./db/test/travis_entrypoint.sh