language: python
python:
  - 3.7
before_install:
  - chmod -R 777 .
install:
  - pip install -r ./client/requirements.txt
branches:
  only: ["master"]
jobs:
  include:
    - stage: client
      script: ./client/test/travis_entrypoint.sh
    - stage: fms
      script: ./fms/test/travis_entrypoint.sh
    - stage: ds
      script: ./ds/test/travis_entrypoint.sh
    - stage: ui
      script: ./ui/test/travis_entrypoint.sh