name: FIRM
version: 0.3.0-SNAPSHOT

camera_port: 0

drawing:
  enabled: false
  face: true
  eyes: true
  nose: true
  mouth: true

image:
  enabled: true
  output_directory: ../data
  type: jpg
  jpg:
    # 0 - 100 (higher means better).
    # Default is 95.
    quality: 95
  png:
    # 0 - 9 (higher means a smaller 
    # size and longer compression time).
    # Default is 3.
    compression: 3
  ppm:
    # 0 or 1
    binary_format_flag: 1
  pgm:
    # 0 or 1
    binary_format_flag: 1
  pbm:
    # 0 or 1
    binary_format_flag: 1

logging:
  enabled: true
  level: INFO
  file: ../log/app.log
  timestamp: true

algorithm:
  extraction_layers:
    - dlib
  haarcascade:
    face_cascade_file: haarcascade/haarcascade_frontalface_default.xml
    eyes_cascade_file: haarcascade/haarcascade_eye_tree_eyeglasses.xml
    nose_cascade_file: haarcascade/haarcascade_mcs_nose.xml
    mouth_cascade_file: haarcascade/haarcascade_mcs_mouth.xml
  caffemodel:
    confidence_threshold: 0.90
    prototxt_file: caffemodel/deploy.prototxt.txt
    caffemodel_file: caffemodel/res10_300x300_ssd_iter_140000.caffemodel
  dlib:
    model: hog
    frame_resize:
      enabled: true
      scale: 0.25