name: FIRM
version: 0.2.0-SNAPSHOT

camera_port: 0

drawing:
  enabled: false
  face: true
  eyes: true
  nose: true
  mouth: true

logging:
  enabled: true
  level: INFO
  file: ../log/app.log
  timestamp: true

algorithm:
  extraction_layers:
    - dlib
  haarcascade:
    face_cascade_file: haarcascade/haarcascade_frontalface_default.xml
    eyes_cascade_file: haarcascade/haarcascade_eye_tree_eyeglasses.xml
    nose_cascade_file: haarcascade/haarcascade_mcs_nose.xml
    mouth_cascade_file: haarcascade/haarcascade_mcs_mouth.xml
  caffemodel:
    confidence_threshold: 0.90
    prototxt_file: caffemodel/deploy.prototxt.txt
    caffemodel_file: caffemodel/res10_300x300_ssd_iter_140000.caffemodel
  dlib:
    frame_resize:
      enabled: true
      scale: 0.25