version: 0.2.0-SNAPSHOT

camera_port: 0

drawing:
  enabled: false
  face: true
  eyes: true
  nose: true
  mouth: true

logging:
  level: INFO
  file: ../log/app.log
  timestamp: true

algorithm:
  face_cascade_file: haarcascade/haarcascade_frontalface_default.xml
  eyes_cascade_file: haarcascade/haarcascade_eye_tree_eyeglasses.xml
  nose_cascade_file: haarcascade/haarcascade_mcs_nose.xml
  mouth_cascade_file: haarcascade/haarcascade_mcs_mouth.xml